### ISSUE TITLE
where to get ladspa plugins?

### ISSUE THREAD

**Issue by mcfiredrill** [JamesHarrison/conduit#1]
Hi!

I was wondering where you get the ladspa plugins that you used in this script. I don't appear to have ladspa.gate even though I installed ocaml-ladspa. Are they in another repository somewhere?

**Comment by JamesHarrison** [comment]
In most distros they're packaged independently. See http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=ladspa&searchon=all for instance.
